version: "3.3"
services:
   http-server-v1:
    build:
      context: ./app
      dockerfile: Dockerfile
    pid: host
    networks:
      - default
    expose:
      - "5555"
    ports:
      - "5555:5555"
    container_name: http-server-v1 
    hostname: http-server-v1 
    restart: always
    volumes:
      - ./app/public:/app/public
      - ./app/storage:/app/storage


networks:
  default:
    external:
      name: ns2021-existing-network